In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [8]:
df=pd.read_csv('spam.csv',encoding='latin_1')
# df.head()
# df.columns

In [9]:
df=df[['v1','v2']]
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.columns=['label','message']
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df['label']=df['label'].map({
    'ham':0,
    'spam':1})

In [12]:
X=df['message']
Y=df['label']

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [14]:
vectorizer=CountVectorizer()
X_train_counts=vectorizer.fit_transform(X_train)
X_test_counts=vectorizer.transform(X_test)

In [15]:
model=MultinomialNB()
model.fit(X_train_counts,Y_train)

MultinomialNB()

In [16]:
prediction=model.predict(X_test_counts)
prediction

array([0, 0, 1, ..., 0, 0, 1])

In [17]:
score=accuracy_score(Y_test,prediction)
score

0.9838565022421525